nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs

packageExtensions:
  '@nx/rspack@*':
    peerDependenciesMeta:
      '@module-federation/enhanced':
        optional: true
      '@module-federation/node':
        optional: true

logFilters:
  - code: YN0086
    text: Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
    level: discard
