nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs

packageExtensions:
  '@module-federation/cli@*':
    dependencies:
      typescript: '*'
  '@module-federation/enhanced@*':
    dependencies:
      '@rspack/core': '*'
      typescript: '*'
  '@module-federation/manifest@*':
    dependencies:
      typescript: '*'
  '@module-federation/dts-plugin@*':
    peerDependenciesMeta:
      typescript:
        optional: true
  '@module-federation/node@*':
    dependencies:
      typescript: '*'
  '@nx/eslint@*':
    dependencies:
      nx: '*'
  '@nx/js@*':
    dependencies:
      nx: '*'
  '@nx/module-federation@*':
    dependencies:
      nx: '*'
      typescript: '*'
  '@nx/playwright@*':
    dependencies:
      eslint: '*'
      nx: '*'
  '@nx/react@*':
    dependencies:
      eslint: '*'
      nx: '*'
      typescript: '*'
  '@nx/rollup@*':
    dependencies:
      '@babel/core': '*'
      nx: '*'
      typescript: '*'
  '@nx/rspack@*':
    dependencies:
      less: '*'
      nx: '*'
      react-refresh: '*'
      typescript: '*'
    peerDependenciesMeta:
      '@module-federation/enhanced':
        optional: true
      '@module-federation/node':
        optional: true
  '@nx/vite@*':
    dependencies:
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      vite:
        optional: true
      vitest:
        optional: true
  '@nx/vitest@*':
    dependencies:
      nx: '*'
      typescript: '*'
  '@nx/web@*':
    dependencies:
      nx: '*'
  '@swc-node/register@*':
    dependencies:
      '@swc/types': '*'
