"""Data ingestion: NHL API, betting odds, league draft history, injuries (US-003..008)."""

from __future__ import annotations

from draft_oracle.ingest.nhl_api import (
    ClubScheduleSeason,
    DailyScores,
    GameLogEntry,
    NHLApiClient,
    NHLApiError,
    PlayerGameLog,
    PlayerLanding,
    PlayoffBracket,
    PlayoffSeries,
    ResponseCache,
    ScheduleGame,
    SkaterSummaryResponse,
    SkaterSummaryRow,
    TeamRoster,
)
from draft_oracle.ingest.normalize import (
    NormalizeResult,
    SnapshotResult,
    build_tables,
    build_team_abbrev_map,
    create_snapshot,
    discover_season_labels,
    list_snapshots,
    map_position,
    normalize_archive,
    normalize_players,
    normalize_series,
    normalize_skater_games,
    normalize_team_games,
    normalize_teams,
)

__all__ = [
    "ClubScheduleSeason",
    "DailyScores",
    "GameLogEntry",
    "NHLApiClient",
    "NHLApiError",
    "NormalizeResult",
    "PlayerGameLog",
    "PlayerLanding",
    "PlayoffBracket",
    "PlayoffSeries",
    "ResponseCache",
    "ScheduleGame",
    "SkaterSummaryResponse",
    "SkaterSummaryRow",
    "SnapshotResult",
    "TeamRoster",
    "build_tables",
    "build_team_abbrev_map",
    "create_snapshot",
    "discover_season_labels",
    "list_snapshots",
    "map_position",
    "normalize_archive",
    "normalize_players",
    "normalize_series",
    "normalize_skater_games",
    "normalize_team_games",
    "normalize_teams",
]
