"""Odds consolidation test collection split by topic."""

from __future__ import annotations

from tests import odds_consolidation_archive_cases as archive
from tests import odds_consolidation_core_cases as core
from tests import odds_consolidation_quality_cases as quality

test_consolidate_prefers_sbr_and_cross_validates = (
    core.test_consolidate_prefers_sbr_and_cross_validates
)
test_consolidate_keeps_adjacent_distinct_games_separate = (
    core.test_consolidate_keeps_adjacent_distinct_games_separate
)
test_consolidate_empty_frame = core.test_consolidate_empty_frame
test_consolidate_snaps_utc_date_to_local = core.test_consolidate_snaps_utc_date_to_local
test_consolidate_keeps_exact_local_date_untouched = (
    core.test_consolidate_keeps_exact_local_date_untouched
)
test_consolidate_no_snap_when_no_archive_match = core.test_consolidate_no_snap_when_no_archive_match
test_load_local_game_dates_indexes_home_away = core.test_load_local_game_dates_indexes_home_away
test_market_join_attaches_genuine_covered_odds = core.test_market_join_attaches_genuine_covered_odds
test_load_archive_game_types_indexes_gametypeid = (
    archive.test_load_archive_game_types_indexes_gametypeid
)
test_consolidate_labels_late_april_regular_as_non_playoff = (
    archive.test_consolidate_labels_late_april_regular_as_non_playoff
)
test_consolidate_labels_playoff_from_gametypeid = (
    archive.test_consolidate_labels_playoff_from_gametypeid
)
test_consolidate_excludes_rows_with_no_archive_game = (
    archive.test_consolidate_excludes_rows_with_no_archive_game
)
test_consolidate_counts_real_reversed_orientation_as_unjoinable = (
    archive.test_consolidate_counts_real_reversed_orientation_as_unjoinable
)
test_playoff_labels_match_committed_archive_gametypeid = (
    archive.test_playoff_labels_match_committed_archive_gametypeid
)
test_parse_kaggle_extensive_flags_constant_placeholder_season = (
    quality.test_parse_kaggle_extensive_flags_constant_placeholder_season
)
test_parse_kaggle_extensive_keeps_genuine_prices_in_dominated_season = (
    quality.test_parse_kaggle_extensive_keeps_genuine_prices_in_dominated_season
)
test_parse_kaggle_extensive_keeps_varied_market_season = (
    quality.test_parse_kaggle_extensive_keeps_varied_market_season
)
test_placeholder_guard_matches_committed_archive = (
    quality.test_placeholder_guard_matches_committed_archive
)
test_committed_kaggle_archive_has_no_attributed_favorites = (
    quality.test_committed_kaggle_archive_has_no_attributed_favorites
)
test_consolidate_xval_gate_flags_source_disagreement = (
    quality.test_consolidate_xval_gate_flags_source_disagreement
)
test_consolidate_xval_gate_flags_opposite_favorite_sides = (
    quality.test_consolidate_xval_gate_flags_opposite_favorite_sides
)
