"""Predictive models: win, shutout, series sim, skater rate, returns, projections (US-011..016).

Public API re-exported for convenience; see :mod:`draft_oracle.models.game_win`.
"""

from draft_oracle.models.game_win import (
    GAME_WIN_MODEL_VERSION,
    MARKET_FEATURE_COLUMNS,
    STAT_FEATURE_COLUMNS,
    GameWinConfig,
    GameWinModel,
    GameWinResult,
    TeamState,
    TemporalSplit,
    baseline_higher_points_probs,
    brier_score,
    build_game_dataset,
    coin_flip_probs,
    default_temporal_split,
    matchup_feature_row,
    train_game_win_from_normalized,
    train_game_win_model,
)
from draft_oracle.models.shutout import (
    NEUTRAL_SAVE_PCT,
    SHUTOUT_FEATURE_COLUMNS,
    SHUTOUT_MODEL_VERSION,
    CalibrationBin,
    ShutoutConfig,
    ShutoutModel,
    ShutoutResult,
    ShutoutTeamState,
    base_rate_probs,
    build_shutout_dataset,
    shutout_feature_row,
    train_shutout_from_normalized,
    train_shutout_model,
)

__all__ = [
    "GAME_WIN_MODEL_VERSION",
    "MARKET_FEATURE_COLUMNS",
    "NEUTRAL_SAVE_PCT",
    "SHUTOUT_FEATURE_COLUMNS",
    "SHUTOUT_MODEL_VERSION",
    "STAT_FEATURE_COLUMNS",
    "CalibrationBin",
    "GameWinConfig",
    "GameWinModel",
    "GameWinResult",
    "ShutoutConfig",
    "ShutoutModel",
    "ShutoutResult",
    "ShutoutTeamState",
    "TeamState",
    "TemporalSplit",
    "base_rate_probs",
    "baseline_higher_points_probs",
    "brier_score",
    "build_game_dataset",
    "build_shutout_dataset",
    "coin_flip_probs",
    "default_temporal_split",
    "matchup_feature_row",
    "shutout_feature_row",
    "train_game_win_from_normalized",
    "train_game_win_model",
    "train_shutout_from_normalized",
    "train_shutout_model",
]
