import {
  createGlobalTheme,
  createGlobalThemeContract,
} from '@vanilla-extract/css';

export const vars = createGlobalThemeContract({
  color: {
    primary: '',
    primaryDark: '',
    primaryLight: '',
    secondary: '',
    accent: '',
    background: '',
    surface: '',
    surfaceHover: '',
    text: '',
    textMuted: '',
    textInverse: '',
    border: '',
    success: '',
    warning: '',
    error: '',
    info: '',
  },
  space: {
    none: '',
    xs: '',
    sm: '',
    md: '',
    lg: '',
    xl: '',
    xxl: '',
  },
  fontSize: {
    xs: '',
    sm: '',
    md: '',
    lg: '',
    xl: '',
    xxl: '',
    xxxl: '',
  },
  fontWeight: {
    normal: '',
    medium: '',
    semibold: '',
    bold: '',
  },
  radius: {
    sm: '',
    md: '',
    lg: '',
    full: '',
  },
  shadow: {
    sm: '',
    md: '',
    lg: '',
  },
});

createGlobalTheme(':root', vars, {
  color: {
    primary: '#1a73e8',
    primaryDark: '#1557b0',
    primaryLight: '#4a9af5',
    secondary: '#6c757d',
    accent: '#ff6b35',
    background: '#f8f9fa',
    surface: '#ffffff',
    surfaceHover: '#f1f3f5',
    text: '#212529',
    textMuted: '#868e96',
    textInverse: '#ffffff',
    border: '#dee2e6',
    success: '#2f9e44',
    warning: '#f59f00',
    error: '#e03131',
    info: '#1971c2',
  },
  space: {
    none: '0',
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
    xxl: '48px',
  },
  fontSize: {
    xs: '0.75rem',
    sm: '0.875rem',
    md: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    xxl: '1.5rem',
    xxxl: '2rem',
  },
  fontWeight: {
    normal: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
  },
  radius: {
    sm: '4px',
    md: '8px',
    lg: '12px',
    full: '9999px',
  },
  shadow: {
    sm: '0 1px 2px rgba(0, 0, 0, 0.05)',
    md: '0 4px 6px rgba(0, 0, 0, 0.1)',
    lg: '0 10px 15px rgba(0, 0, 0, 0.15)',
  },
});
